# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:            Wan-Ting Huang
tagline:          'Data Science'
description:      'Taiwanese. Love sharing.'
url:              http://lanyon.getpoole.com
baseurl:             ''
paginate:            1
excerpt_separator:  '<!-- more -->'

# About/contact
author:
  name:              Wan-Ting Huang
  url:               https://wantinghuang.github.io
  email:             wanting0913@gmail.com
  gravatar_md5:      2089b63e10c8c2e2af39df77ef525622
  
# Custom vars
version:          1.0.0

# Gems
plugins: [jekyll-paginate]
paginate_path: "page:num"

future: false
